# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_alpha_opt <- function(C, W, mu) {
    .Call('gflasso_get_alpha_opt', PACKAGE = 'gflasso', C, W, mu)
}

