# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Get optimal alpha matrix from the dual norm representation
#' @param B The J x K regression coefficient estimates.
#' @param C The L1 penalization matrix, returned by \code{get_C()}.
#' @param mu The smoothing parameter.
#' @return The optimal A matrix defined by Lemma 1.
#' @references Smoothing Proximal Gradient Method for General Structured Sparse Regression
#' @export
#' @useDynLib gflasso
get_alpha_opt <- function(C, W, mu) {
    .Call('gflasso_get_alpha_opt', PACKAGE = 'gflasso', C, W, mu)
}

